version: 0.8.0
name: sealed_currencies
description: Provides data for world currencies in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_currencies
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
  - currencies
  - currency
  - money
  - iso-4217
  - iso

screenshots:
  - description: "Structure visualization"
    path: doc/structure.webp
  - description: "Examples of usage"
    path: doc/example.webp

environment:
  sdk: ^3.0.0

dependencies:
  sealed_languages: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.6 # From Google
  coverage: ^1.7.1 # From Google
  dart_code_metrics: # Flutter Favorite
    git:
      url: https://github.com/tsinis/dart-code-metrics
  lints: ^3.0.0 # From Google
  test: ^1.24.9 # From Google
