version: 2.0.0
name: sealed_currencies
description: Provides data for world currencies in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_currencies
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
  - currencies
  - currency
  - money
  - iso-4217
  - iso

screenshots:
  - description: "Structure visualization"
    path: doc/structure.webp
  - description: "Examples of usage"
    path: doc/example.webp

environment:
  sdk: ^3.6.0

dependencies:
  sealed_languages: ^2.0.0

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  build_runner: ^2.4.14 # From Google
  coverage: ^1.11.1 # From Google
  dart_code_metrics_presets: ^2.20.0
  lints: ^5.1.1 # From Google
  test: ^1.25.14 # From Google
