version: 1.5.0
name: sealed_currencies
description: Provides data for world currencies in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_currencies
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
  - currencies
  - currency
  - money
  - iso-4217
  - iso

screenshots:
  - description: "Structure visualization"
    path: doc/structure.webp
  - description: "Examples of usage"
    path: doc/example.webp

environment:
  sdk: ^3.0.0

dependencies:
  sealed_languages: ^1.5.0

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  build_runner: ^2.4.9 # From Google
  coverage: ^1.7.2 # From Google
  dart_code_linter: ^1.1.3 # Ex-DCM.
  dart_code_metrics_presets: ^2.16.0
  lints: ^4.0.0 # From Google
  test: ^1.25.4 # From Google
