version: 1.0.0
name: _sealed_world_tests
description: Test infra for writing sealed world tests. Is not published.
publish_to: none
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/_sealed_world_tests
issue_tracker: https://github.com/tsinis/sealed_world/issues

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  meta: any # Constrained in the workspace pubspec.yaml
  test: any # Constrained in the workspace pubspec.yaml

dev_dependencies:
  dart_code_metrics_presets: any # Constrained in the workspace pubspec.yaml
