version: 1.0.0
name: l10n_countries
description: Provides country names translations (for 194 different locales).
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/l10n_countries
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
  - l10n
  - localization
  - country
  - translations
  - countries

screenshots:
  - description: "Code quality"
    path: doc/quality.webp
  - description: "Examples of usage"
    path: doc/example.webp

resolution: workspace

environment:
  sdk: ^3.6.0

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  coverage: ^1.11.1 # From Google
  dart_code_metrics_presets: ^2.21.0
  lints: ^5.1.1 # From Google
  test: ^1.25.8 # From Google
