version: 0.2.0
name: sealed_languages
description: Provides data for world languages in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_languages
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
 - languages
 - language
 - locale
 - sealed
 - iso-639
 - iso

screenshots:
  - description: 'Examples of usage'
    path: doc/example.webp


environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.4 # From Google
  dart_code_metrics: ^5.7.4 # Flutter Favorite
  lints: ^2.1.0 # From Google
  test: ^1.24.3 # From Google
