version: 2.1.0
name: sealed_countries
description: Provides data for world countries in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_countries
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
  - countries
  - country
  - land
  - iso-3166
  - flags

screenshots:
  - description: "Code quality"
    path: doc/quality.webp
  - description: "Structure visualization"
    path: doc/structure.webp
  - description: "Examples of usage"
    path: doc/example.webp

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  l10n_countries: ^1.0.0
  sealed_currencies: ^2.1.0

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  build_runner: ^2.4.14 # From Google
  coverage: ^1.11.1 # From Google
  dart_code_metrics_presets: ^2.20.0
  lints: ^5.1.1 # From Google
  test: ^1.25.8 # From Google
