version: 0.1.0
name: sealed_countries
description: Provides data for world countries in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_countries
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
 - countries
 - country
 - land
 - sealed
 - iso-3166
 - iso

screenshots:
  - description: 'Examples of usage'
    path: doc/example.webp

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sealed_currencies: ^0.1.0
  sealed_languages: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.4 # From Google
  dart_code_metrics: ^5.7.4 # Flutter Favorite
  lints: ^2.1.0 # From Google
  test: ^1.24.3 # From Google
