version: 3.0.1
name: sealed_countries
description: Provides data for world countries in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_countries
issue_tracker: https://github.com/tsinis/sealed_world/issues

resolution: workspace

topics:
  - countries
  - country
  - land
  - iso-3166
  - flags

screenshots:
  - description: "Code quality"
    path: doc/quality.webp
  - description: "Structure visualization"
    path: doc/structure.webp
  - description: "Examples of usage"
    path: doc/example.webp

environment:
  sdk: ^3.10.8

dependencies:
  l10n_countries: ^2.0.0
  sealed_currencies: ^3.0.0

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  dart_code_metrics_presets: any # Constrained in the workspace pubspec.yaml
  test: any # Constrained in the workspace pubspec.yaml
