name: sealed_countries
description: Provides data for world countries in the form of sealed classes.
version: 0.0.1

publish_to: 'none' # TODO! Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sealed_currencies:
    path: ../sealed_currencies
  sealed_languages:
    path: ../sealed_languages

dev_dependencies:
  build_runner: ^2.4.4 # From Google
  dart_code_metrics: ^5.7.3 # Flutter Favorite
  lints: ^2.1.0 # From Google
  test: ^1.24.2 # From Google
