version: 0.5.0
name: sealed_countries
description: Provides data for world countries in the form of sealed classes.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/sealed_countries
issue_tracker: https://github.com/tsinis/sealed_world/issues
topics:
 - countries
 - country
 - land
 - iso-3166
 - iso

screenshots:
  - description: 'Structure visualization'
    path: doc/structure.webp
  - description: 'Examples of usage'
    path: doc/example.webp

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sealed_currencies: ^0.5.0
  sealed_languages: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.6 # From Google
  coverage: ^1.6.3 # From Google
  dart_code_metrics: ^5.7.6 # Flutter Favorite
  lints: ^2.1.1 # From Google
  test: ^1.24.6 # From Google
