version: 3.0.1
name: world_flags
description: The first and only collection of declaratively defined world flags. No assets.
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/world_flags
issue_tracker: https://github.com/tsinis/sealed_world/issues
homepage: https://tsin.is/sealed_world/#/country/gbr/settings

resolution: workspace

topics:
  - flags
  - flag
  - country-flags
  - country-flag
  - coat-of-arms

screenshots:
  - description: "Example of usage"
    path: doc/example.webp

# This package supports all official Flutter platforms:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  sealed_countries: ^3.0.1

dev_dependencies:
  _sealed_world_tests:
    path: ../_sealed_world_tests
  dart_code_metrics_presets: any # Constrained in the workspace pubspec.yaml
  flutter_test: # From Google
    sdk: flutter

flutter:
  shaders:
    - shaders/waved_flag.frag
