name: world_flags_example
description: A world_flags package example application.
publish_to: none
version: 2.0.1+0

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

dev_dependencies:
  dart_code_metrics_presets: ^2.20.0
  flutter_test: # From Google
    sdk: flutter
  lints: ^5.1.1 # From Google

flutter:
  uses-material-design: true
