name: example
description: A world_flags package example application.
publish_to: none

version: 1.1.0+0

environment:
  sdk: ^3.4.4
  flutter: ^3.22.3

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

dev_dependencies:
  dart_code_metrics_presets: ^2.16.0
  flutter_test: # From Google
    sdk: flutter
  lints: ^4.0.0 # From Google

flutter:
  uses-material-design: true
