version: 2.9.1
name: world_flags_example
description: A world_flags package example application.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

flutter:
  uses-material-design: false
