version: 3.0.0
name: world_flags_example
description: A world_flags package example application.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

flutter:
  uses-material-design: true
  shaders:
    - shaders/cupertino_emoji_flag.frag
