name: world_flags_example
description: A world_flags package example application.
publish_to: none
version: 2.1.0

resolution: workspace

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  world_flags:
    path: ../

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  lints: ^5.1.1 # From Google
