name: cli
publish_to: none
description: Command-line tools for a sealed_world ecosystem.
version: 0.0.4

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  change_case: ^2.2.0
  collection: ^1.19.0
  path: ^1.9.0
  pure_dart_ui: ^0.1.10
  rw_git: ^1.0.3
  sealed_countries:
    path: ../packages/sealed_countries
  sealed_currencies: any
  sealed_languages: any
  select_annotation: ^0.2.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.14 # From Google
  dart_code_metrics_presets: ^2.21.0
