name: cli
description: Command-line tools for a sealed_world eco-system.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  change_case: ^1.1.0
  path: ^1.8.3 # From Google
  rw_git: ^1.0.3
  sealed_languages:
    path: ../packages/sealed_languages
  select_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6 # From Google
  dart_code_metrics: # Flutter Favorite
    git:
      url: https://github.com/tsinis/dart-code-metrics
  select: ^0.4.1
