version: 0.1.2
name: cli
description: Command-line tools for a sealed_world ecosystem.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.7.0
  change_case: ^2.2.0
  collection: ^1.19.1
  path: ^1.9.1
  pure_dart_ui: ^0.1.10
  sealed_countries:
    path: ../packages/sealed_countries
  sealed_currencies: any
  sealed_languages: any
  yaml: ^3.1.3
