version: 2.0.0
name: l10n_currencies
description: Provides currency names translations (for 149 different locales).
maintainer: Roman Cinis
repository: https://github.com/tsinis/sealed_world/tree/main/packages/l10n_currencies
issue_tracker: https://github.com/tsinis/sealed_world/issues

resolution: workspace

topics:
  - l10n
  - localization
  - currency
  - translations
  - currencies

screenshots:
  - description: "Code quality"
    path: doc/quality.webp
  - description: "Examples of usage"
    path: doc/example.webp

environment:
  sdk: ^3.10.4

dev_dependencies:
  test: any # Constrained in the workspace pubspec.yaml
