name: countries_flutter

on:
  # push: # TODO: After publishing as open source.
  pull_request:
    branches: [main]
    paths:
      - "packages/countries_flutter/**"
      - ".github/workflows/countries_flutter.yaml"

jobs:
  verify-countries-flutter:
    uses: ./.github/workflows/flutter_package_workflow.yaml
    with:
      package_name: countries_flutter