name: currencies_dart

on:
  push:
    branches: [main]
    paths:
      - "packages/currencies_dart/**"
      - ".github/workflows/currencies_dart.yaml"
  pull_request:
    branches: [main]
    paths:
      - "packages/currencies_dart/**"
      - ".github/workflows/currencies_dart.yaml"

jobs:
  verify-currencies-dart:
    uses: ./.github/workflows/dart_package_workflow.yaml
    with:
      package_name: currencies_dart