name: languages_dart

on:
  # push: # TODO: After publishing as open source.
  pull_request:
    paths:
      - "packages/languages_dart/**"
      - ".github/workflows/languages_dart.yaml"

jobs:
  verify-currencies-dart:
    uses: ./.github/workflows/dart_package_workflow.yaml
    with:
      package_name: languages_dart